create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  razorpay_order_id text not null unique,
  razorpay_payment_id text not null unique,
  customer_name text not null,
  customer_email text not null,
  amount integer not null check (amount > 0),
  currency text not null check (currency in ('INR', 'USD')),
  status text not null default 'paid',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
